# see: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates
# see: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"    
    reviewers:
      - "yuokada"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"    
    reviewers:
      - "yuokada"
      
